source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 4.0'
    pod 'ProcedureKit/Mobile'
end

target 'Notes' do
  shared_pods
end

target 'Core' do
    shared_pods
end

target 'AirBank' do
    shared_pods
end
