source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Notes' do
  pod 'Alamofire', '~> 4.0'
  pod 'ProcedureKit/Mobile', '~> 4.0'
  pod 'RxSwift', '~> 4.4'
  pod 'RxCocoa', '~> 4.4'
end
